name: Release

on:
  push:
    tags: ['*.*.*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Build
      run: make -j

    - name: Archive files
      run: |
        xz -9 UTF-8
        tar -Jcvf unicode.tar.xz unicode

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.xz
          runewidth_table.go
          tables.rs
          wcwidth9.h
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
