name: Release

on:
  push:
    tags: ['*.*.*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Setup poetry
      run: |
        wget -qO- ${GET_POETRY_URI} | python3 - --no-modify-path
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      env:
        GET_POETRY_URI: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py

    - name: Setup GNU Make >= 4.3
      run: brew install make

    - name: poetry install
      run: poetry install --no-dev

    - name: Build
      run: make -j

    - name: Compress UTF-8
      run: xz -9 UTF-8

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          EastAsianWidth.generated.txt
          UTF-8.xz
          runewidth_table.go
          tables.rs
          wcwidth9.h
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
